<a href="https://colab.research.google.com/github/TanujaMore27/Deep-Learning/blob/main/5_pytorch_nn_module_pipeline_with_dataset_and_dataloader.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from sklearn.datasets import make_classification
import torch

In [2]:
X,y = make_classification(
    n_features=2,
    n_samples=10,
    n_redundant=0,
    n_informative=2,
    n_classes=2,
    random_state=42
)

In [3]:
X

array([[ 1.06833894, -0.97007347],
       [-1.14021544, -0.83879234],
       [-2.8953973 ,  1.97686236],
       [-0.72063436, -0.96059253],
       [-1.96287438, -0.99225135],
       [-0.9382051 , -0.54304815],
       [ 1.72725924, -1.18582677],
       [ 1.77736657,  1.51157598],
       [ 1.89969252,  0.83444483],
       [-0.58723065, -1.97171753]])

In [4]:
X.shape

(10, 2)

In [5]:
y

array([1, 0, 0, 0, 0, 1, 1, 1, 1, 0])

In [6]:
y.shape

(10,)

In [8]:
X = torch.tensor(X, dtype=torch.float32)
y = torch.tensor(y,dtype=torch.long)

/tmp/ipykernel_8839/3276321781.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  X = torch.tensor(X, dtype=torch.float32)

In [9]:
from torch.utils.data import Dataset,DataLoader

In [10]:
class CustomDataset(Dataset):
  def __init__(self,features,labels):
    self.features=features
    self.labels = labels

  def __len__(self):
    return self.features.shape[0]

  def __getitem__(self,index):
    return self.features[index],self.labels[index]

In [11]:
dataset = CustomDataset(X,y)

In [12]:
len(dataset)

10

In [13]:
dataset[2]

(tensor([-2.8954,  1.9769]), tensor(0))

In [14]:
dataloader = DataLoader(dataset,batch_size=2,shuffle=False)

In [15]:
for batch_features, batch_labels in dataloader:

  print(batch_features)
  print(batch_labels)
  print("-"*50)

tensor([[ 1.0683, -0.9701],
        [-1.1402, -0.8388]])
tensor([1, 0])
--------------------------------------------------
tensor([[-2.8954,  1.9769],
        [-0.7206, -0.9606]])
tensor([0, 0])
--------------------------------------------------
tensor([[-1.9629, -0.9923],
        [-0.9382, -0.5430]])
tensor([0, 1])
--------------------------------------------------
tensor([[ 1.7273, -1.1858],
        [ 1.7774,  1.5116]])
tensor([1, 1])
--------------------------------------------------
tensor([[ 1.8997,  0.8344],
        [-0.5872, -1.9717]])
tensor([1, 0])
--------------------------------------------------

In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [3]:
df.shape

(569, 33)

In [4]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [5]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [6]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [7]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [8]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [9]:
X_train.shape

(455, 30)

In [10]:
X_train_tensor = torch.from_numpy(X_train.astype(np.float32))
X_test_tensor = torch.from_numpy(X_test.astype(np.float32))
y_train_tensor = torch.from_numpy(y_train.astype(np.float32))
y_test_tensor = torch.from_numpy(y_test.astype(np.float32))

In [11]:
X_train_tensor.shape

torch.Size([455, 30])

In [15]:
from torch.utils.data import Dataset,DataLoader

class Custom(Dataset):
  def __init__(self,features,labels):
    self.features=features
    self.labels=labels

  def __len__(self):
    return len(self.features)

  def __getitem__(self,idx):
    return self.features[idx],self.labels[idx]

In [16]:
train_dataset = Custom(X_train_tensor,y_train_tensor)
test_dataset = Custom(X_test_tensor,y_test_tensor)

In [17]:
train_dataset[0]

(tensor([-0.0210, -0.7599, -0.0842, -0.1227, -0.8398, -0.8474, -0.6643, -0.4939,
         -0.3683, -0.5238, -0.0574, -0.3134, -0.1062, -0.1632,  0.2884, -0.7151,
         -0.5706, -0.4397, -0.0706, -0.3791, -0.1194, -0.6536, -0.1711, -0.2240,
         -0.5716, -0.8022, -0.7476, -0.5880, -0.2765, -0.6157]),
 tensor(0.))

In [18]:
train_loader = DataLoader(train_dataset,batch_size=32,shuffle=True)
test_loader = DataLoader(test_dataset,batch_size=32,shuffle=True)

In [29]:
import torch.nn as nn

class MySimpleNN(nn.Module):
  def __init__(self,num_features):
    super().__init__()
    self.linear = nn.Linear(num_features,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self,features):
    out = self.linear(features)
    out = self.sigmoid(out)
    return out

In [30]:
lr = 0.1
epochs = 25

In [31]:
model = MySimpleNN(X_train_tensor.shape[1])

optimizer = torch.optim.SGD(model.parameters(),lr)

loss_function = nn.BCELoss()

In [32]:
for epoch in range(epochs):
  for batch_features,batch_labels in train_loader:
    y_pred = model(batch_features)

    loss = loss_function(y_pred,batch_labels.view(-1,1))

    optimizer.zero_grad()

    loss.backward()

    optimizer.step()

    print(f'epoch:{epoch+1}, Loss:{loss.item()}')

epoch:1, Loss:0.721465528011322
epoch:1, Loss:0.525232195854187
epoch:1, Loss:0.5144455432891846
epoch:1, Loss:0.36427128314971924
epoch:1, Loss:0.3554893136024475
epoch:1, Loss:0.27002614736557007
epoch:1, Loss:0.2908709645271301
epoch:1, Loss:0.2423529177904129
epoch:1, Loss:0.2824224531650543
epoch:1, Loss:0.242044597864151
epoch:1, Loss:0.1757591962814331
epoch:1, Loss:0.3694725036621094
epoch:1, Loss:0.20963270962238312
epoch:1, Loss:0.19589941203594208
epoch:1, Loss:0.21387319266796112
epoch:2, Loss:0.22326919436454773
epoch:2, Loss:0.21392127871513367
epoch:2, Loss:0.16604720056056976
epoch:2, Loss:0.20251429080963135
epoch:2, Loss:0.15891849994659424
epoch:2, Loss:0.1304291933774948
epoch:2, Loss:0.29273736476898193
epoch:2, Loss:0.1227528378367424
epoch:2, Loss:0.11608222872018814
epoch:2, Loss:0.16116729378700256
epoch:2, Loss:0.16836535930633545
epoch:2, Loss:0.16492904722690582
epoch:2, Loss:0.17077328264713287
epoch:2, Loss:0.10149042308330536
epoch:2, Loss:0.19640056788921356
epoch:3, Loss:0.09851622581481934
epoch:3, Loss:0.17363576591014862
epoch:3, Loss:0.23534370958805084
epoch:3, Loss:0.06983937323093414
epoch:3, Loss:0.18327520787715912
epoch:3, Loss:0.1857161521911621
epoch:3, Loss:0.13194525241851807
epoch:3, Loss:0.0878954827785492
epoch:3, Loss:0.13794076442718506
epoch:3, Loss:0.14880730211734772
epoch:3, Loss:0.14053303003311157
epoch:3, Loss:0.1203957349061966
epoch:3, Loss:0.09134795516729355
epoch:3, Loss:0.09998451918363571
epoch:3, Loss:0.18092072010040283
epoch:4, Loss:0.0651170089840889
epoch:4, Loss:0.1493016630411148
epoch:4, Loss:0.13504400849342346
epoch:4, Loss:0.10522300750017166
epoch:4, Loss:0.14010226726531982
epoch:4, Loss:0.08222763985395432
epoch:4, Loss:0.1606331467628479
epoch:4, Loss:0.16879811882972717
epoch:4, Loss:0.08647340536117554
epoch:4, Loss:0.11414358019828796
epoch:4, Loss:0.09870999306440353
epoch:4, Loss:0.06122996285557747
epoch:4, Loss:0.2156057059764862
epoch:4, Loss:0.10482605546712875
epoch:4, Loss:0.040905337780714035
epoch:5, Loss:0.11502616852521896
epoch:5, Loss:0.14010782539844513
epoch:5, Loss:0.11053275316953659
epoch:5, Loss:0.1210547611117363
epoch:5, Loss:0.07819755375385284
epoch:5, Loss:0.08991534262895584
epoch:5, Loss:0.0878768265247345
epoch:5, Loss:0.1529577672481537
epoch:5, Loss:0.13332565128803253
epoch:5, Loss:0.08957350999116898
epoch:5, Loss:0.07722455263137817
epoch:5, Loss:0.13606926798820496
epoch:5, Loss:0.08284229040145874
epoch:5, Loss:0.12527751922607422
epoch:5, Loss:0.022111859172582626
epoch:6, Loss:0.08361367136240005
epoch:6, Loss:0.16497929394245148
epoch:6, Loss:0.10130459815263748
epoch:6, Loss:0.11919556558132172
epoch:6, Loss:0.11696045100688934
epoch:6, Loss:0.08305393159389496
epoch:6, Loss:0.10548722743988037
epoch:6, Loss:0.06855534017086029
epoch:6, Loss:0.09449434280395508
epoch:6, Loss:0.09530705213546753
epoch:6, Loss:0.08451300859451294
epoch:6, Loss:0.08088357001543045
epoch:6, Loss:0.10488706827163696
epoch:6, Loss:0.06911823153495789
epoch:6, Loss:0.30429956316947937
epoch:7, Loss:0.04888859763741493
epoch:7, Loss:0.056442636996507645
epoch:7, Loss:0.13245317339897156
epoch:7, Loss:0.11879250407218933
epoch:7, Loss:0.13200737535953522
epoch:7, Loss:0.060927413403987885
epoch:7, Loss:0.06868159025907516
epoch:7, Loss:0.11911751329898834
epoch:7, Loss:0.10901729762554169
epoch:7, Loss:0.0677318125963211
epoch:7, Loss:0.15075252950191498
epoch:7, Loss:0.0826222375035286
epoch:7, Loss:0.13259564340114594
epoch:7, Loss:0.05101994425058365
epoch:7, Loss:0.10329757630825043
epoch:8, Loss:0.051669299602508545
epoch:8, Loss:0.13744069635868073
epoch:8, Loss:0.11114044487476349
epoch:8, Loss:0.05617064610123634
epoch:8, Loss:0.12245677411556244
epoch:8, Loss:0.10929755866527557
epoch:8, Loss:0.14334440231323242
epoch:8, Loss:0.0853901132941246
epoch:8, Loss:0.11121542751789093
epoch:8, Loss:0.0800287202000618
epoch:8, Loss:0.07574083656072617
epoch:8, Loss:0.04824666678905487
epoch:8, Loss:0.05610959604382515
epoch:8, Loss:0.09595835208892822
epoch:8, Loss:0.036770280450582504
epoch:9, Loss:0.06586332619190216
epoch:9, Loss:0.0698661208152771
epoch:9, Loss:0.09157105535268784
epoch:9, Loss:0.07102753967046738
epoch:9, Loss:0.0441352054476738
epoch:9, Loss:0.14218653738498688
epoch:9, Loss:0.15525786578655243
epoch:9, Loss:0.06278276443481445
epoch:9, Loss:0.10737329721450806
epoch:9, Loss:0.118057981133461
epoch:9, Loss:0.04052301123738289
epoch:9, Loss:0.10423051565885544
epoch:9, Loss:0.06217597797513008
epoch:9, Loss:0.069730743765831
epoch:9, Loss:0.1805734634399414
epoch:10, Loss:0.12812182307243347
epoch:10, Loss:0.0869884192943573
epoch:10, Loss:0.10046087205410004
epoch:10, Loss:0.1967838704586029
epoch:10, Loss:0.11212272942066193
epoch:10, Loss:0.0669068694114685
epoch:10, Loss:0.10395257920026779
epoch:10, Loss:0.04493410885334015
epoch:10, Loss:0.05341918393969536
epoch:10, Loss:0.040231019258499146
epoch:10, Loss:0.04242657497525215
epoch:10, Loss:0.08741308003664017
epoch:10, Loss:0.07094749063253403
epoch:10, Loss:0.06532297283411026
epoch:10, Loss:0.017787883058190346
epoch:11, Loss:0.11553625017404556
epoch:11, Loss:0.148631751537323
epoch:11, Loss:0.06694269925355911
epoch:11, Loss:0.05000408738851547
epoch:11, Loss:0.08029409497976303
epoch:11, Loss:0.06996580213308334
epoch:11, Loss:0.10694122314453125
epoch:11, Loss:0.08034753799438477
epoch:11, Loss:0.08318190276622772
epoch:11, Loss:0.1093919426202774
epoch:11, Loss:0.04700661078095436
epoch:11, Loss:0.08420296013355255
epoch:11, Loss:0.05658923462033272
epoch:11, Loss:0.06411105394363403
epoch:11, Loss:0.032375872135162354
epoch:12, Loss:0.061535533517599106
epoch:12, Loss:0.08973991125822067
epoch:12, Loss:0.06454584002494812
epoch:12, Loss:0.06568040698766708
epoch:12, Loss:0.13403666019439697
epoch:12, Loss:0.04576074704527855
epoch:12, Loss:0.08581852167844772
epoch:12, Loss:0.05053265392780304
epoch:12, Loss:0.05174709111452103
epoch:12, Loss:0.1345406174659729
epoch:12, Loss:0.08511588722467422
epoch:12, Loss:0.14173950254917145
epoch:12, Loss:0.06347406655550003
epoch:12, Loss:0.060350190848112106
epoch:12, Loss:0.02992001175880432
epoch:13, Loss:0.05265290290117264
epoch:13, Loss:0.23027652502059937
epoch:13, Loss:0.057547427713871
epoch:13, Loss:0.09488363564014435
epoch:13, Loss:0.10217444598674774
epoch:13, Loss:0.045608848333358765
epoch:13, Loss:0.12410814315080643
epoch:13, Loss:0.10482674092054367
epoch:13, Loss:0.04990090802311897
epoch:13, Loss:0.08992428332567215
epoch:13, Loss:0.026079818606376648
epoch:13, Loss:0.03247452154755592
epoch:13, Loss:0.04930935800075531
epoch:13, Loss:0.03402205556631088
epoch:13, Loss:0.10250889509916306
epoch:14, Loss:0.09701848775148392
epoch:14, Loss:0.08699695020914078
epoch:14, Loss:0.05823349207639694
epoch:14, Loss:0.16424143314361572
epoch:14, Loss:0.15302306413650513
epoch:14, Loss:0.05518988147377968
epoch:14, Loss:0.07506627589464188
epoch:14, Loss:0.053668975830078125
epoch:14, Loss:0.029648466035723686
epoch:14, Loss:0.05723286420106888
epoch:14, Loss:0.04481051489710808
epoch:14, Loss:0.07338744401931763
epoch:14, Loss:0.08654727041721344
epoch:14, Loss:0.0537920780479908
epoch:14, Loss:0.022398972883820534
epoch:15, Loss:0.01945374719798565
epoch:15, Loss:0.08526459336280823
epoch:15, Loss:0.019709128886461258
epoch:15, Loss:0.1819968819618225
epoch:15, Loss:0.08743924647569656
epoch:15, Loss:0.06338275223970413
epoch:15, Loss:0.05656075105071068
epoch:15, Loss:0.05511070042848587
epoch:15, Loss:0.03993913158774376
epoch:15, Loss:0.0755540281534195
epoch:15, Loss:0.18695035576820374
epoch:15, Loss:0.08732236176729202
epoch:15, Loss:0.04626740142703056
epoch:15, Loss:0.044499270617961884
epoch:15, Loss:0.11352144181728363
epoch:16, Loss:0.05845960974693298
epoch:16, Loss:0.027772294357419014
epoch:16, Loss:0.0561920590698719
epoch:16, Loss:0.1814098358154297
epoch:16, Loss:0.1158032938838005
epoch:16, Loss:0.026718273758888245
epoch:16, Loss:0.12400410324335098
epoch:16, Loss:0.04230332374572754
epoch:16, Loss:0.05798863247036934
epoch:16, Loss:0.03240025043487549
epoch:16, Loss:0.06424813717603683
epoch:16, Loss:0.06468702107667923
epoch:16, Loss:0.12986108660697937
epoch:16, Loss:0.06771303713321686
epoch:16, Loss:0.03716821223497391
epoch:17, Loss:0.09214981645345688
epoch:17, Loss:0.048377975821495056
epoch:17, Loss:0.01319934707134962
epoch:17, Loss:0.0563422366976738
epoch:17, Loss:0.0786208063364029
epoch:17, Loss:0.06009228900074959
epoch:17, Loss:0.10081589221954346
epoch:17, Loss:0.029638584703207016
epoch:17, Loss:0.06722339242696762
epoch:17, Loss:0.23397448658943176
epoch:17, Loss:0.06023889780044556
epoch:17, Loss:0.037468452006578445
epoch:17, Loss:0.10594296455383301
epoch:17, Loss:0.052601512521505356
epoch:17, Loss:0.015249245800077915
epoch:18, Loss:0.052165914326906204
epoch:18, Loss:0.047958504408597946
epoch:18, Loss:0.13409298658370972
epoch:18, Loss:0.06189076602458954
epoch:18, Loss:0.10742361098527908
epoch:18, Loss:0.01951635628938675
epoch:18, Loss:0.06445783376693726
epoch:18, Loss:0.04316316917538643
epoch:18, Loss:0.048889730125665665
epoch:18, Loss:0.1158953458070755
epoch:18, Loss:0.05200359970331192
epoch:18, Loss:0.15319021046161652
epoch:18, Loss:0.08663054555654526
epoch:18, Loss:0.024736391380429268
epoch:18, Loss:0.06265757232904434
epoch:19, Loss:0.0855824425816536
epoch:19, Loss:0.056145794689655304
epoch:19, Loss:0.023878145962953568
epoch:19, Loss:0.04832407832145691
epoch:19, Loss:0.06656458973884583
epoch:19, Loss:0.04126143082976341
epoch:19, Loss:0.11686067283153534
epoch:19, Loss:0.04064390808343887
epoch:19, Loss:0.04489406198263168
epoch:19, Loss:0.055441003292798996
epoch:19, Loss:0.07684953510761261
epoch:19, Loss:0.06320079416036606
epoch:19, Loss:0.2419705092906952
epoch:19, Loss:0.048660971224308014
epoch:19, Loss:0.010016931220889091
epoch:20, Loss:0.03769718483090401
epoch:20, Loss:0.08397448062896729
epoch:20, Loss:0.0657431036233902
epoch:20, Loss:0.05102340131998062
epoch:20, Loss:0.05809289589524269
epoch:20, Loss:0.158769428730011
epoch:20, Loss:0.08155699819326401
epoch:20, Loss:0.05617520958185196
epoch:20, Loss:0.06453023105859756
epoch:20, Loss:0.04689206928014755
epoch:20, Loss:0.17089036107063293
epoch:20, Loss:0.056921493262052536
epoch:20, Loss:0.04747841879725456
epoch:20, Loss:0.017233045771718025
epoch:20, Loss:0.021002283319830894
epoch:21, Loss:0.04175230860710144
epoch:21, Loss:0.09795714914798737
epoch:21, Loss:0.05246281251311302
epoch:21, Loss:0.022140370681881905
epoch:21, Loss:0.10718130320310593
epoch:21, Loss:0.07698255032300949
epoch:21, Loss:0.009119356982409954
epoch:21, Loss:0.031723957508802414
epoch:21, Loss:0.19520825147628784
epoch:21, Loss:0.07924580574035645
epoch:21, Loss:0.0644744336605072
epoch:21, Loss:0.05956118553876877
epoch:21, Loss:0.10906068235635757
epoch:21, Loss:0.01802004501223564
epoch:21, Loss:0.10899436473846436
epoch:22, Loss:0.04986083507537842
epoch:22, Loss:0.10561779141426086
epoch:22, Loss:0.07906921207904816
epoch:22, Loss:0.011604291386902332
epoch:22, Loss:0.035757921636104584
epoch:22, Loss:0.03680192679166794
epoch:22, Loss:0.03841739147901535
epoch:22, Loss:0.16559043526649475
epoch:22, Loss:0.06229986995458603
epoch:22, Loss:0.034765735268592834
epoch:22, Loss:0.03758225217461586
epoch:22, Loss:0.047050364315509796
epoch:22, Loss:0.14106610417366028
epoch:22, Loss:0.12731434404850006
epoch:22, Loss:0.02326839603483677
epoch:23, Loss:0.032370228320360184
epoch:23, Loss:0.08292511105537415
epoch:23, Loss:0.03787827119231224
epoch:23, Loss:0.13165049254894257
epoch:23, Loss:0.018598191440105438
epoch:23, Loss:0.04592372849583626
epoch:23, Loss:0.20289123058319092
epoch:23, Loss:0.07391553372144699
epoch:23, Loss:0.08619735389947891
epoch:23, Loss:0.05302780866622925
epoch:23, Loss:0.026723191142082214
epoch:23, Loss:0.04863779619336128
epoch:23, Loss:0.037591464817523956
epoch:23, Loss:0.0551094152033329
epoch:23, Loss:0.1616625338792801
epoch:24, Loss:0.0573856346309185
epoch:24, Loss:0.03766737878322601
epoch:24, Loss:0.18674278259277344
epoch:24, Loss:0.040750421583652496
epoch:24, Loss:0.07579616457223892
epoch:24, Loss:0.01554783247411251
epoch:24, Loss:0.0594584085047245
epoch:24, Loss:0.17153675854206085
epoch:24, Loss:0.02831922098994255
epoch:24, Loss:0.08346403390169144
epoch:24, Loss:0.019565973430871964
epoch:24, Loss:0.08163044601678848
epoch:24, Loss:0.06617973744869232
epoch:24, Loss:0.03244361653923988
epoch:24, Loss:0.010441185906529427
epoch:25, Loss:0.09804069995880127
epoch:25, Loss:0.027063224464654922
epoch:25, Loss:0.060128457844257355
epoch:25, Loss:0.020192669704556465
epoch:25, Loss:0.1833958625793457
epoch:25, Loss:0.05645843967795372
epoch:25, Loss:0.04730852693319321
epoch:25, Loss:0.04972417652606964
epoch:25, Loss:0.04486234486103058
epoch:25, Loss:0.01295291818678379
epoch:25, Loss:0.06755414605140686
epoch:25, Loss:0.13581658899784088
epoch:25, Loss:0.025944074615836143
epoch:25, Loss:0.1182415783405304
epoch:25, Loss:0.008333053439855576

In [33]:
# Model evaluation using test_loader
model.eval()  # Set the model to evaluation mode
accuracy_list = []

with torch.no_grad():
    for batch_features, batch_labels in test_loader:
        # Forward pass
        y_pred = model(batch_features)
        y_pred = (y_pred > 0.8).float()  # Convert probabilities to binary predictions

        # Calculate accuracy for the current batch
        batch_accuracy = (y_pred.view(-1) == batch_labels).float().mean().item()
        accuracy_list.append(batch_accuracy)

# Calculate overall accuracy
overall_accuracy = sum(accuracy_list) / len(accuracy_list)
print(f'Accuracy: {overall_accuracy:.4f}')

Accuracy: 0.9062